### ISSUE TITLE
1.20.4 Server crashing upon [REDACTED]

### ISSUE THREAD

**Issue by iMakeMacintosh** [kaweepatinn1/kaweepatinn1.github.io#11]
Hey, I'm having difficulty with my 1.20.4 server crashing when I [REDACTED]. Please help me.

I have provided everything you need to login.
![bsod](https://github.com/kaweepatinn1/kaweepatinn1.github.io/assets/169651727/1ea831ec-2ba3-4578-bf36-0e0a82d32bb1)

**Comment by kaweepatinn1** [comment]
Feel free to discuss this with me on the support discord: https://discord.gg/ugm3bGAZPs

~ _Quote of the day_ ~
**The opened cookie jar reveals the treats hidden inside**

**Comment by yihangyu2** [comment]
jsut cremae dmy pantz
