### ISSUE TITLE
None of the links work

### ISSUE THREAD

**Issue by 09lkei** [kaweepatinn1/kaweepatinn1.github.io#2]
**Describe the bug**
When I click on a link it goes to a blank page

**To Reproduce**
1. Go to nanomotions.org
2. Click any of the links apart from film

**Expected behavior**
The link to go to another page

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version most recent

**Comment by kaweepatinn1** [comment]
Will fix when I actually make the pages

**Comment by mayankpm** [comment]
you've made a mistake, it tries to open a link that doesn't exist. Like in this case, Nanomotions.html doesn't even exist, either build a Nanomotions.html or use an existing link for now

**Comment by kaweepatinn1** [comment]
Fixed in [deploy 66](https://github.com/kaweepatinn1/kaweepatinn1.github.io/actions/runs/6065099110)
